const TRAVEL_DATA = {
  "dataset_version": "2026.04",
  "currency": "USD",
  "months": {
    "January": [
      {
        "month": "January",
        "country": "Thailand",
        "best_cities_or_regions": ["Bangkok", "Chiang Mai", "Krabi", "Koh Lanta"],
        "why_visit": "January is peak dry season with clear skies and comfortable temperatures, ideal for Andaman beaches and northern trekking. It's the sweet spot after New Year crowds thin slightly but weather remains near-perfect.",
        "climate": {"avg_temp_c": "24-32", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "40-80",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Bo Sang Umbrella Festival (Chiang Mai, late Jan)",  "Chinese New Year celebrations in Chinatown (late Jan/early Feb)", "Chiang Mai Flower Festival lead-up"],
        "travel_styles": ["beach", "food", "culture", "nightlife"],
        "pros": ["Excellent dry-season weather", "Affordable food and lodging", "Huge range of beach and cultural options", "Great domestic flight network"],
        "cons": ["Very crowded on top islands",  "Accommodation prices peak", "Air quality worsens in northern Thailand late month"]
      },
      {
        "month": "January",
        "country": "Argentina",
        "best_cities_or_regions": ["Buenos Aires", "El Calafate", "El Chaltén", "Bariloche"],
        "why_visit": "January is the heart of Patagonian summer with long daylight hours perfect for trekking Fitz Roy and visiting Perito Moreno Glacier. Buenos Aires buzzes with open-air tango and parrilla culture.",
        "climate": {"avg_temp_c": "10-22", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "80-160",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Festival Nacional del Folklore de Cosquín (late Jan)", "Patagonia peak trekking season", "Buenos Aires summer tango milongas"],
        "travel_styles": ["adventure", "nature", "culture", "food"],
        "pros": ["Ideal hiking weather in Patagonia",  "Long daylight for photography",  "World-class steak and wine", "Vibrant capital nightlife"],
        "cons": ["Patagonia lodging books out months ahead",  "High domestic flight prices", "Inflation makes costs unpredictable"] 
      },
      {
        "month": "January",
        "country": "Japan",
        "best_cities_or_regions": ["Niseko", "Furano", "Sapporo", "Hakuba"],
        "why_visit": "January delivers Hokkaido's legendary 'Japow' — some of the driest, deepest powder on earth — making it the world's top skiing month. Onsen towns and Sapporo's winter illuminations add culture and warmth.",
        "climate": {"avg_temp_c": "-8 to 2", "rainfall_level": "high", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "200-400",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Sapporo White Illumination (through mid-Jan)", "Otaru Snow Light Path preparations", "Coming of Age Day (2nd Monday)"],
        "travel_styles": ["skiing", "wellness", "food", "culture"],
        "pros": ["World-class powder skiing", "Excellent onsen and ryokan culture", "Clean, safe, efficient infrastructure", "Stunning winter scenery"],
        "cons": ["Niseko prices rival Swiss resorts", "Accommodation sells out 6+ months ahead", "Very cold with short daylight"]
      },
      {
        "month": "January",
        "country": "Costa Rica",
        "best_cities_or_regions": ["Manuel Antonio", "Monteverde", "Arenal/La Fortuna", "Tamarindo"],
        "why_visit": "January falls in the dry season with reliable sunshine, ideal for rainforest hikes, zip-lining, and Pacific surfing. Wildlife viewing is excellent as animals gather around shrinking water sources.", 
        "climate": {"avg_temp_c": "22-30", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "100-180",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Fiestas de Palmares (mid-Jan)", "Fiesta de Santa Cruz (Guanacaste)", "Envision Festival preparations"],
        "travel_styles": ["adventure", "nature", "wildlife", "beach"],
        "pros": ["Reliable dry-season weather", "Outstanding biodiversity and wildlife", "Adventure activities in abundance", "English widely spoken"],
        "cons": ["High-season prices", "Popular parks and beaches crowded",  "Domestic travel can be slow"]
      },
      {
        "month": "January",
        "country": "New Zealand",
        "best_cities_or_regions": ["Queenstown", "Wanaka", "Abel Tasman", "Rotorua"],
        "why_visit": "January is peak Kiwi summer with warm temperatures, long days, and optimal conditions for Great Walks, glacier hikes, and beach days — the best month for alpine and lake adventures on the South Island.",
        "climate": {"avg_temp_c": "14-24", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "120-220",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Wanaka A&P Show preparations", "Auckland Anniversary Day regatta (late Jan)", "Summer Great Walks fully open"],
        "travel_styles": ["adventure", "nature", "wellness", "food"],
        "pros": ["Excellent hiking and outdoor weather",  "Long daylight until ~9pm", "Stunning landscapes and low crime", "Great wine regions open"],
        "cons": ["Summer holiday crowds at popular spots",  "Peak prices for campervans and lodging",  "Sandflies in wilderness areas"]
      }
    ],
    "February": [
      {
        "month": "February",
        "country": "Tanzania",
        "best_cities_or_regions": ["Ndutu", "Ngorongoro Crater", "Zanzibar", "Arusha"],
        "why_visit": "February is peak wildebeest calving season in the Ndutu region of the southern Serengeti, with thousands of calves born daily  and dramatic predator activity. Zanzibar offers warm, relatively dry beach days to pair with safari.",
        "climate": {"avg_temp_c": "18-28", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "500-900",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Wildebeest calving peak in Ndutu",  "Sauti za Busara music festival (Zanzibar, mid-Feb)", "Kilimanjaro Marathon prep"],
        "travel_styles": ["wildlife", "nature", "adventure", "beach"],
        "pros": ["Greatest wildlife spectacle on Earth at peak", "High predator sightings", "Lush green Serengeti landscapes", "Zanzibar combo for beach extension"],
        "cons": ["Expensive mobile camps book 9-12 months ahead",  "Occasional afternoon rains and muddy tracks", "Long international flights required"]
      },
      {
        "month": "February",
        "country": "Mexico",
        "best_cities_or_regions": ["Oaxaca", "Mexico City", "Yucatán", "Baja California Sur"],
        "why_visit": "February brings perfect dry, warm weather to the Yucatán and Baja, with gray whale watching in San Ignacio Lagoon at its peak.  Oaxaca is mild and vibrant, ideal for mezcal, markets, and Zapotec culture.",
        "climate": {"avg_temp_c": "16-28", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "70-140",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Gray whale season in Baja (peak Feb)",  "Carnaval de Mazatlán & Veracruz (mid-Feb)", "Día de la Candelaria (Feb 2)"],
        "travel_styles": ["culture", "food", "wildlife", "beach"],
        "pros": ["Excellent weather almost everywhere", "World-class food and mezcal scene", "Gray whale encounters in Baja", "Good value for the region"],
        "cons": ["Cancún/Tulum crowded with spring breakers late month", "Rising prices in boutique Yucatán towns", "Safety varies by region"]
      },
      {
        "month": "February",
        "country": "Norway",
        "best_cities_or_regions": ["Tromsø", "Lofoten Islands", "Alta", "Senja"],
        "why_visit": "February offers some of the best aurora borealis viewing conditions with long dark nights and stable weather, plus prime season for dog sledding, whale watching, and Sámi cultural experiences.",
        "climate": {"avg_temp_c": "-6 to 2", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "250-450",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Northern Lights Festival Tromsø (late Jan/early Feb)", "Sámi National Day (Feb 6)", "Sámi Week & Reindeer Race (Tromsø)"],
        "travel_styles": ["nature", "adventure", "wildlife", "culture"],
        "pros": ["Prime aurora viewing window", "Unique Arctic activities (dog sledding, whale watching)", "Safe, easy infrastructure", "Stunning snow-covered landscapes"],
        "cons": ["Very expensive",  "Tours book 4-6 months ahead", "Alcohol and dining costs extreme"]
      },
      {
        "month": "February",
        "country": "Vietnam",
        "best_cities_or_regions": ["Hoi An", "Ho Chi Minh City", "Mekong Delta", "Phu Quoc"],
        "why_visit": "February is peak dry season in the south with sunny warm weather perfect for beaches and the Mekong. Tết (Lunar New Year) falls Feb 17, 2026, offering a colorful glimpse of Vietnamese tradition.",
        "climate": {"avg_temp_c": "20-30", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "35-75",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Tết (Lunar New Year, Feb 17, 2026)",  "Perfume Pagoda Festival (Feb-Mar)", "Da Lat Flower Festival aftermath"],
        "travel_styles": ["food", "culture", "beach", "adventure"],
        "pros": ["Excellent weather in south/central",  "Exceptional street food and low costs", "Rich culture during Tết period", "Diverse scenery from beaches to mountains"],
        "cons": ["Many small businesses close during Tết week",  "Domestic transport sells out around Tết",  "Northern Vietnam still cool and misty"] 
      },
      {
        "month": "February",
        "country": "Brazil",
        "best_cities_or_regions": ["Rio de Janeiro", "Salvador", "Olinda/Recife", "São Paulo"],
        "why_visit": "February 2026 hosts Rio Carnival (Feb 13-21),  the world's largest street party, with Sambadrome parades Feb 15-17.  Beach weather is at peak summer intensity along Copacabana and Ipanema.",
        "climate": {"avg_temp_c": "24-35", "rainfall_level": "medium", "humidity": "high"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "100-250",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Rio Carnival (Feb 13-21, 2026)", "Salvador Carnival (same dates)", "Champions' Parade (Feb 21)"], 
        "travel_styles": ["nightlife", "culture", "beach", "food"],
        "pros": ["World's most iconic party atmosphere", "Spectacular Sambadrome parades and free blocos", "Gorgeous beaches and tropical summer", "Rich Afro-Brazilian culture on display"],
        "cons": ["Prices 2-3x normal during Carnival week",  "Pickpocketing common in crowds",  "Hot, humid, physically exhausting"]
      },
      {
        "month": "February",
        "country": "Australia",
        "best_cities_or_regions": ["Sydney", "Tasmania", "Port Douglas", "Melbourne"],
        "why_visit": "February is late austral summer with warm seas ideal for snorkeling the Great Barrier Reef and Tasmania's long days perfect for hiking. Sydney's Mardi Gras builds toward early March.",
        "climate": {"avg_temp_c": "18-28", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "180-320",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Sydney Gay and Lesbian Mardi Gras (runs into early March)", "Perth Festival (throughout Feb)", "Tropfest short film festival"],
        "travel_styles": ["beach", "nature", "adventure", "food"],
        "pros": ["Warm sea temps for reef snorkeling", "Long daylight hours", "Excellent food and wine scenes", "Tasmania ideal for summer hiking"],
        "cons": ["Cyclone risk in tropical north", "Box jellyfish in northern waters", "Expensive flights and accommodation"]
      }
    ],
    "March": [
      {
        "month": "March",
        "country": "Japan",
        "best_cities_or_regions": ["Tokyo", "Kyoto", "Osaka", "Nara"],
        "why_visit": "Late March is cherry blossom peak in central Japan — 2026 forecasts first bloom in Tokyo around March 19 and full bloom March 27.  Mild spring weather is ideal for temple visits and hanami picnics.",
        "climate": {"avg_temp_c": "6-15", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-280",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Cherry blossom (sakura) season", "Omizutori fire festival (Nara, Mar 1-14)", "Hina Matsuri (Mar 3)"],
        "travel_styles": ["culture", "food", "nature", "wellness"],
        "pros": ["Iconic sakura viewing", "Pleasant mild spring weather", "Exceptional food and hospitality", "Efficient rail network for blossom-chasing"],
        "cons": ["Peak bloom crowds at top hanami spots", "Hotel rates surge for bloom week", "Bloom timing unpredictable"]
      },
      {
        "month": "March",
        "country": "Jordan",
        "best_cities_or_regions": ["Petra", "Wadi Rum", "Amman", "Dead Sea"],
        "why_visit": "March brings mild temperatures and wildflower blooms, making it ideal for hiking Petra's trails and camping in Wadi Rum without summer's extreme heat. Shoulder season means fewer crowds at ancient sites.", 
        "climate": {"avg_temp_c": "10-22", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "90-170",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Jordan Trail thru-hiking season", "Wildflower blooms in northern highlands",  "Ramadan tail end (impacts hours)"],
        "travel_styles": ["culture", "adventure", "nature", "wellness"],
        "pros": ["Ideal hiking weather at Petra and Wadi Rum",  "Fewer tourists than April peak", "Clear desert skies for stargazing",  "Safe, welcoming country"],
        "cons": ["Reduced hours during Ramadan", "Chilly desert nights",  "Occasional rain in north"]
      },
      {
        "month": "March",
        "country": "South Africa",
        "best_cities_or_regions": ["Cape Town", "Kruger National Park", "Stellenbosch", "Garden Route"],
        "why_visit": "March is late summer with warm, dry Cape weather ideal for Table Mountain hikes and wine harvest in Stellenbosch. Kruger game viewing improves as the bush dries out and high-season crowds haven't arrived.",
        "climate": {"avg_temp_c": "15-27", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "100-200",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Cape Town Cycle Tour (early March)", "Cape Town International Jazz Festival (late March)", "Stellenbosch wine harvest festivals"],
        "travel_styles": ["wildlife", "food", "nature", "adventure"],
        "pros": ["Great weather in Cape region", "Wine harvest season at peak", "Good safari value vs peak winter", "Strong USD/EUR value"],
        "cons": ["Bush still fairly thick for Kruger spotting", "Occasional heat waves", "Safety concerns in some urban areas"]
      },
      {
        "month": "March",
        "country": "Iceland",
        "best_cities_or_regions": ["Reykjavík", "South Coast", "Snæfellsnes Peninsula", "Jökulsárlón"],
        "why_visit": "March is the final strong month for northern lights with lengthening daylight for ice caves, glacier hikes, and waterfall tours — the best balance of winter scenery and accessible days.",
        "climate": {"avg_temp_c": "-2 to 4", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "200-380",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["DesignMarch Reykjavík (late March)", "Beer Day (Mar 1)", "Final ice cave tour window"],
        "travel_styles": ["nature", "adventure", "wellness"],
        "pros": ["Aurora still frequently visible", "Balanced daylight (~11-13 hrs by end of month)", "Last chance for natural blue ice caves",  "Fewer tourists than summer peak"],
        "cons": ["Weather highly unpredictable", "Very expensive food and tours", "Road conditions can close routes"]
      },
      {
        "month": "March",
        "country": "Sri Lanka",
        "best_cities_or_regions": ["Kandy", "Ella", "Galle", "Yala National Park"],
        "why_visit": "March is dry-season prime for the southern and western coasts, offering beach-and-safari combos, leopard tracking at Yala, and the cool tea-country hills of Ella and Nuwara Eliya.",
        "climate": {"avg_temp_c": "24-32", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "45-100",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Medin Poya (full moon religious observance)", "Whale watching season at Mirissa",  "Tea harvest tours in hill country"],
        "travel_styles": ["beach", "wildlife", "culture", "nature"],
        "pros": ["Excellent weather on south/west coast",  "Great value across lodging and food", "World-class leopard safari at Yala",  "Diverse circuit in a small country"],
        "cons": ["East coast still in off-season rainy pattern",  "Yala can be crowded at top sightings", "Heat builds toward end of month"]
      }
    ],
    "April": [
      {
        "month": "April",
        "country": "Netherlands",
        "best_cities_or_regions": ["Amsterdam", "Keukenhof/Lisse", "Rotterdam", "The Hague"],
        "why_visit": "April is peak tulip season at Keukenhof Gardens and the flower fields of Lisse, culminating in the nationwide orange-clad street party of King's Day (Koningsdag) on April 27.", 
        "climate": {"avg_temp_c": "5-13", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "130-220",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Keukenhof Gardens open season", "Koningsdag (April 27)", "Bloemencorso Bollenstreek flower parade (late April)"],
        "travel_styles": ["culture", "nature", "food", "nightlife"],
        "pros": ["Iconic tulip fields in full bloom", "Vibrant King's Day nationwide festival", "Compact, bike-friendly cities", "Excellent museums and canal architecture"],
        "cons": ["Very crowded at Keukenhof and Amsterdam", "Unpredictable showers and cool temps", "Accommodation prices spike around Koningsdag"]
      },
      {
        "month": "April",
        "country": "Japan",
        "best_cities_or_regions": ["Kyoto", "Tokyo", "Hirosaki", "Takayama"],
        "why_visit": "Early April catches the tail of the cherry blossom front moving north through Tokyo and Kyoto, while late April blooms peak in Tohoku, pairing with mild spring hiking weather.",
        "climate": {"avg_temp_c": "10-19", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "120-250",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Cherry blossom season", "Takayama Spring Festival (April 14-15)", "Hirosaki Cherry Blossom Festival", "Miyako Odori geisha dances in Kyoto"],
        "travel_styles": ["culture", "food", "nature", "wellness"],
        "pros": ["Iconic hanami cherry blossom experience", "Pleasant mild weather for sightseeing", "World-class food and rail network", "Beautiful temples framed by sakura"],
        "cons": ["Peak prices and packed hotspots", "Bloom timing unpredictable", "Flights and shinkansen book out early"]
      },
      {
        "month": "April",
        "country": "Peru",
        "best_cities_or_regions": ["Cusco", "Machu Picchu", "Sacred Valley", "Arequipa"],
        "why_visit": "April marks the end of the Andes' rainy season — landscapes are lush green but skies clear dramatically, offering excellent Inca Trail conditions just before the May-September high season rush.",
        "climate": {"avg_temp_c": "7-20", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "60-130",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Semana Santa processions in Cusco and Ayacucho", "Señor de los Temblores procession", "Inca Trail reopens April 1"],
        "travel_styles": ["adventure", "culture", "nature", "food"],
        "pros": ["Green landscapes with fewer crowds", "Shoulder-season pricing", "Inca Trail just reopened and less booked", "Vibrant Holy Week religious pageantry"],
        "cons": ["Occasional heavy rain and possible landslides", "Altitude sickness risk in Cusco", "Muddy trails in the Sacred Valley"]
      },
      {
        "month": "April",
        "country": "Bhutan",
        "best_cities_or_regions": ["Paro", "Thimphu", "Punakha", "Bumthang"],
        "why_visit": "April offers clear Himalayan views, blooming rhododendrons, and the Paro Tsechu festival (Mar 29-Apr 2, 2026) with masked cham dances and the unfurling of the giant Guru Thongdrel thangka.",
        "climate": {"avg_temp_c": "8-20", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "280-450",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Paro Tsechu (Mar 29-Apr 2, 2026)", "Rhododendron Festival at Lamperi (mid-April)", "Ura Yakchoe (late April)"],
        "travel_styles": ["culture", "adventure", "nature", "wellness"],
        "pros": ["One of Bhutan's most spectacular festivals", "Clear mountain views and blooming rhododendrons", "Ideal trekking weather (Tiger's Nest)", "Low tourist density"],
        "cons": ["Mandatory $100/night Sustainable Development Fee", "Expensive overall and limited flights", "Paro Tsechu sells out months ahead"]
      },
      {
        "month": "April",
        "country": "Australia",
        "best_cities_or_regions": ["Sydney", "Uluru/Red Centre", "Cairns", "Melbourne"],
        "why_visit": "Early autumn in Australia brings warm dry days with lower humidity, ideal for outback travel and reef diving, plus Anzac Day commemorations (April 25) offering a deep cultural experience.",
        "climate": {"avg_temp_c": "14-24", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-260",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Anzac Day (April 25)", "Melbourne International Comedy Festival", "Sydney Royal Easter Show", "Parrtjima light festival, Alice Springs"],
        "travel_styles": ["beach", "nature", "wildlife", "culture", "adventure"],
        "pros": ["Comfortable autumn temperatures nationwide", "Reef visibility excellent with low stinger risk", "Outback and Uluru at their best", "Fewer crowds than summer peak"],
        "cons": ["Long-haul flights expensive", "School-holiday pricing around Easter", "Cooler evenings in southern cities"]
      }
    ],
    "May": [
      {
        "month": "May",
        "country": "Italy",
        "best_cities_or_regions": ["Rome", "Amalfi Coast", "Florence", "Puglia"],
        "why_visit": "May delivers warm Mediterranean weather before summer's heat and crowds, with wildflowers across Tuscany and Puglia and pre-peak prices along the Amalfi Coast.",
        "climate": {"avg_temp_c": "14-23", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-280",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Italian Open tennis in Rome", "Infiorata flower-carpet festivals (Genzano, Noto)", "Giro d'Italia", "Maggio Musicale Fiorentino"],
        "travel_styles": ["culture", "food", "beach", "wellness"],
        "pros": ["Ideal weather, warm sea, no August inferno", "Lower prices than June-August", "Lush countryside and blooming landscapes", "Outdoor dining in perfect temperatures"],
        "cons": ["Rome and Florence still very busy", "Sea still cool in early May", "Popular coastal hotels fill quickly"]
      },
      {
        "month": "May",
        "country": "Botswana",
        "best_cities_or_regions": ["Okavango Delta", "Chobe National Park", "Moremi Game Reserve", "Makgadikgadi Pans"],
        "why_visit": "May marks the start of the dry winter season as the Okavango floodwaters peak — wildlife concentrates around waterways, making it prime time for mokoro safaris before peak-season pricing kicks in.",
        "climate": {"avg_temp_c": "10-28", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "600-1500",
        "season_type": "shoulder",
        "crowd_level": "low",
        "key_events": ["Okavango Delta flood peak", "Start of dry-season game viewing", "Maun cultural events"],
        "travel_styles": ["wildlife", "nature", "adventure"],
        "pros": ["Peak flood in the Delta, excellent mokoro canoeing", "Cooler drier weather with clearer skies", "Shoulder-season rates at many camps", "Exceptional game viewing"],
        "cons": ["Very expensive fly-in safari camps", "Cold nights and early mornings", "Limited budget-travel infrastructure"]
      },
      {
        "month": "May",
        "country": "France",
        "best_cities_or_regions": ["Paris", "French Riviera", "Provence", "Loire Valley"],
        "why_visit": "May is peak shoulder season across France with blooming lavender preludes, the Cannes Film Festival (May 12-23, 2026), and the Monaco Grand Prix lighting up the Riviera.",
        "climate": {"avg_temp_c": "11-21", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-300",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Cannes Film Festival (May 12-23, 2026)", "Monaco Grand Prix (late May)", "Roland-Garros French Open (late May)", "Nuit des Musées"],
        "travel_styles": ["culture", "food", "nightlife", "beach"],
        "pros": ["Glamorous Riviera events and star-spotting", "Mild sunny weather ideal for Paris walks", "Long daylight hours and café terraces", "Excellent wine-country visits"],
        "cons": ["Cannes/Monaco weeks cause price spikes", "Paris crowds building toward summer peak", "Frequent May public-holiday closures"]
      },
      {
        "month": "May",
        "country": "Indonesia",
        "best_cities_or_regions": ["Bali", "Yogyakarta", "Komodo/Flores", "Lombok"],
        "why_visit": "May kicks off Bali's dry season with sunny days, calm seas, and low humidity — perfect for surfing, diving Komodo, and joining Vesak (Waisak) celebrations at Borobudur.",
        "climate": {"avg_temp_c": "23-31", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "40-100",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Vesak/Waisak Day at Borobudur (full moon in May)", "Bali Spirit Festival", "Start of dry season and surf season"],
        "travel_styles": ["beach", "culture", "wellness", "adventure", "food"],
        "pros": ["Dry, sunny weather with low humidity", "Great value for money", "Excellent surf and dive conditions", "Iconic Vesak lantern release at Borobudur"],
        "cons": ["Popular beaches getting busy", "Komodo boats sell out quickly", "Traffic congestion in south Bali"]
      },
      {
        "month": "May",
        "country": "Canada",
        "best_cities_or_regions": ["Vancouver", "Banff/Lake Louise", "Quebec City", "Niagara"],
        "why_visit": "Canada emerges from winter in May with blooming gardens, thawing lakes in the Rockies, and pre-summer pricing, while spring whale-watching begins off both coasts.",
        "climate": {"avg_temp_c": "7-18", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "130-240",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Canadian Tulip Festival, Ottawa (mid-May)", "Victoria Day long weekend (May 18, 2026)", "Stratford Festival season opens", "Spring whale-watching (BC and Quebec)"],
        "travel_styles": ["nature", "adventure", "wildlife", "culture"],
        "pros": ["National parks open but uncrowded", "Lake Louise begins to thaw to iconic turquoise", "Long daylight hours for road trips", "Good wildlife viewing"],
        "cons": ["Rockies lakes may still be partially frozen early May", "Variable weather — snow possible", "Some high-altitude trails still closed"]
      }
    ],
    "June": [
      {
        "month": "June",
        "country": "Iceland",
        "best_cities_or_regions": ["Reykjavík", "South Coast", "Westfjords", "Akureyri"],
        "why_visit": "June brings the midnight sun (peaking around the June 21 solstice) with nearly 24 hours of daylight, puffin colonies on coastal cliffs, and all highland F-roads beginning to open.",
        "climate": {"avg_temp_c": "8-13", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "250-450",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Summer Solstice / Jónsmessa (June 24)", "Icelandic National Day (June 17)", "Midnight Sun Run in Reykjavík", "Secret Solstice Festival"],
        "travel_styles": ["nature", "adventure", "wildlife", "wellness"],
        "pros": ["Almost 24-hour daylight", "Puffin and whale-watching season at peak", "All ring road and most highland routes accessible", "Driest month of the year"],
        "cons": ["Flights and hotels 40-60% more expensive", "Popular sites very crowded", "No chance of Northern Lights"]
      },
      {
        "month": "June",
        "country": "Kenya",
        "best_cities_or_regions": ["Masai Mara", "Amboseli", "Samburu", "Lamu"],
        "why_visit": "June ends the long rains and begins the dry season; wildlife concentrates around water sources and the Great Migration herds start pushing north toward the Mara, just ahead of the July crowd surge.",
        "climate": {"avg_temp_c": "12-26", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "250-600",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Great Migration herds begin entering Kenya late June", "Madaraka Day (June 1)", "Lamu Cultural Festival prep"],
        "travel_styles": ["wildlife", "adventure", "culture", "beach"],
        "pros": ["Early migration action without peak prices", "Dry weather and clear sightlines", "Green post-rain landscapes", "Less crowded than July-October peak"],
        "cons": ["Migration river crossings not yet guaranteed", "Chilly early mornings", "Top camps still pricey"]
      },
      {
        "month": "June",
        "country": "Slovenia",
        "best_cities_or_regions": ["Ljubljana", "Lake Bled", "Soča Valley", "Piran"],
        "why_visit": "June offers warm, sunny weather with long daylight hours before July crowds — perfect for swimming in Lake Bled, rafting the Soča, and hiking the Julian Alps with wildflowers in bloom.",
        "climate": {"avg_temp_c": "13-24", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "100-180",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Statehood Day (June 25)", "Ljubljana Festival opening", "Lent Festival prep (Maribor)", "Summer hiking season begins in Triglav NP"],
        "travel_styles": ["nature", "adventure", "culture", "food"],
        "pros": ["Beautiful alpine and coastal scenery", "Warm lakes and rivers swimmable", "Excellent value vs neighbors", "Great hiking and whitewater conditions"],
        "cons": ["Occasional afternoon thunderstorms", "Lake Bled gets tour-bus crowds midday", "Limited direct international flights"]
      },
      {
        "month": "June",
        "country": "Mongolia",
        "best_cities_or_regions": ["Ulaanbaatar", "Gobi Desert", "Terelj National Park", "Khövsgöl Lake"],
        "why_visit": "June offers green steppes in full bloom, foals running on the plains, and mild pre-summer weather — an ideal window before July's Naadam crowds while still catching local countryside Naadams.",
        "climate": {"avg_temp_c": "10-24", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "80-180",
        "season_type": "shoulder",
        "crowd_level": "low",
        "key_events": ["Green-steppe season with foal births", "Local countryside Naadams begin late June", "Thousand Camel Festival prep"],
        "travel_styles": ["adventure", "culture", "nature", "wildlife"],
        "pros": ["Lush green steppe landscapes", "Mild temperatures for Gobi travel", "Far fewer tourists than July peak", "Lower Naadam-season pricing"],
        "cons": ["Limited tourism infrastructure outside UB", "Long off-road drives between sights", "Weather can shift fast on the steppe"]
      },
      {
        "month": "June",
        "country": "Brazil",
        "best_cities_or_regions": ["Rio de Janeiro", "Manaus (Amazon)", "Salvador", "Pantanal"],
        "why_visit": "June is the start of Brazil's dry season in the Amazon and Pantanal — ideal for wildlife spotting — while the Northeast celebrates Festas Juninas, South America's biggest rural-folk festival cycle.",
        "climate": {"avg_temp_c": "18-27", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "70-160",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Festas Juninas (São João) in Campina Grande and Caruaru", "Parintins Folklore Festival (late June)", "Start of Pantanal jaguar-sighting window"],
        "travel_styles": ["culture", "wildlife", "nature", "food", "nightlife"],
        "pros": ["Massive São João street festivals", "Prime jaguar-spotting in Pantanal begins", "Mild, dry winter weather in Rio", "Shoulder-season prices"],
        "cons": ["Ocean cooler for beach days in Rio", "Amazon travel logistics complex", "Some safety concerns in urban areas"]
      }
    ],
    "July": [
      {
        "month": "July",
        "country": "Tanzania",
        "best_cities_or_regions": ["Northern Serengeti", "Grumeti Reserve", "Ngorongoro Crater", "Zanzibar"],
        "why_visit": "July is prime dry-season safari time as the Great Migration herds push north, with dramatic Grumeti River crossings in the Western Corridor and early Mara River crossings beginning in the northern Serengeti.",
        "climate": {"avg_temp_c": "14-27", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "400-900",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Great Migration Grumeti & early Mara River crossings", "Peak dry-season game viewing"],
        "travel_styles": ["wildlife", "adventure", "nature", "beach"],
        "pros": ["Best month for river crossings and predator action", "Cool, dry, malaria-reduced weather", "Easy to combine Serengeti with Zanzibar", "Excellent photography light"],
        "cons": ["Very expensive; lodges book 6-12 months ahead", "Crowded at popular river crossings", "Cold early mornings on game drives"]
      },
      {
        "month": "July",
        "country": "Mongolia",
        "best_cities_or_regions": ["Ulaanbaatar", "Terelj National Park", "Gobi Desert", "Kharkhorin"],
        "why_visit": "July hosts the UNESCO-listed Naadam Festival (July 11-13, 2026) with wrestling, archery and horse racing, and is the warmest, greenest time on the steppe — ideal for nomadic ger stays and horseback travel.",
        "climate": {"avg_temp_c": "13-24", "rainfall_level": "medium", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "80-180",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Naadam Festival (July 11-13, 2026)", "Countryside Naadams in Khovd, Bayan-Ölgii & Khatgal"],
        "travel_styles": ["culture", "adventure", "nature"],
        "pros": ["Once-in-a-lifetime cultural spectacle", "Lush green steppe ideal for riding and camping", "Long daylight and warm days", "Combines well with Gobi"],
        "cons": ["UB hotels raise prices 40-80% around Naadam", "Brief heavy afternoon thunderstorms", "Dusty, rough overland travel"]
      },
      {
        "month": "July",
        "country": "Iceland",
        "best_cities_or_regions": ["Reykjavík", "South Coast", "Westfjords", "Highlands"],
        "why_visit": "July is Iceland's warmest, driest month with up to 21 hours of daylight and the midnight sun, opening F-roads into the Highlands and peak puffin and whale-watching season along the coast.",
        "climate": {"avg_temp_c": "9-15", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "200-400",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Midnight Sun (near-24hr daylight)", "Puffin nesting season", "Peak whale watching in Húsavík"],
        "travel_styles": ["nature", "adventure", "wellness"],
        "pros": ["Mildest weather and all Ring Road + Highland F-roads accessible", "Endless daylight for late-night hiking", "Excellent whale and puffin viewing", "Festivals and long outdoor evenings"],
        "cons": ["Peak-season pricing", "Major sites very crowded", "No chance to see northern lights"]
      },
      {
        "month": "July",
        "country": "Indonesia",
        "best_cities_or_regions": ["Bali", "Nusa Penida", "Komodo National Park", "Gili Islands"],
        "why_visit": "July sits in the heart of the dry season — sunny, low-humidity days with calm seas perfect for diving Komodo, surfing the Bukit Peninsula and exploring Bali's cultural heart without monsoon interruptions.",
        "climate": {"avg_temp_c": "23-30", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "50-120",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Bali Arts Festival (mid-June to mid-July, Denpasar)", "Dry-season surfing at Uluwatu/Padang Padang"],
        "travel_styles": ["beach", "culture", "adventure", "wellness", "food"],
        "pros": ["Reliable sunshine and minimal rainfall", "Best underwater visibility for diving", "Excellent value vs Western destinations", "Major cultural programming during Bali Arts Festival"],
        "cons": ["Popular beaches and Ubud very busy", "Accommodation prices 30-50% above shoulder", "Traffic congestion in south Bali"]
      },
      {
        "month": "July",
        "country": "Canada",
        "best_cities_or_regions": ["Banff & Jasper", "Vancouver", "Québec City", "Montréal"],
        "why_visit": "July brings warm long summer days ideal for hiking the Rockies, wildlife spotting, and catching Canada's marquee summer festivals in Montréal and Calgary.",
        "climate": {"avg_temp_c": "15-26", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-300",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Calgary Stampede (early July)", "Montréal International Jazz Festival", "Just for Laughs Montréal (mid-late July)"],
        "travel_styles": ["nature", "adventure", "culture", "food"],
        "pros": ["Peak hiking weather in the Rockies", "Whale watching peak on both coasts", "Huge roster of world-class festivals", "Long daylight hours in the north"],
        "cons": ["National park lodging very crowded", "Summer hotel rates at yearly highs", "Wildfire smoke can affect western regions"]
      },
      {
        "month": "July",
        "country": "Greece",
        "best_cities_or_regions": ["Santorini", "Crete", "Milos", "Athens"],
        "why_visit": "July delivers classic Mediterranean summer — dry, sun-soaked days, warm Aegean waters for island-hopping, and open-air Athens Epidaurus Festival performances in ancient theatres.",
        "climate": {"avg_temp_c": "23-33", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "150-350",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Athens Epidaurus Festival (June-August)", "Meltemi winds (great for sailing)", "Rockwave Festival Athens"],
        "travel_styles": ["beach", "culture", "food", "nightlife"],
        "pros": ["Virtually guaranteed sunshine and swimmable seas", "Full ferry schedules for island-hopping", "Vibrant nightlife on Mykonos, Ios, Paros", "Ancient sites performed live at Epidaurus"],
        "cons": ["Santorini/Mykonos extremely crowded", "Peak-season hotel prices often double shoulder", "Athens heatwaves can exceed 38°C"]
      }
    ],
    "August": [
      {
        "month": "August",
        "country": "Spain",
        "best_cities_or_regions": ["Valencia/Buñol", "San Sebastián", "Mallorca", "Barcelona"],
        "why_visit": "August is fiesta season across Spain, anchored by La Tomatina in Buñol on Aug 26, 2026, alongside San Sebastián's Semana Grande and Mallorca's beach-perfect weather.",
        "climate": {"avg_temp_c": "20-32", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "120-250",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["La Tomatina (Aug 26, 2026, Buñol)", "Semana Grande San Sebastián (mid-August)", "Feria de Málaga (mid-August)"],
        "travel_styles": ["culture", "beach", "food", "nightlife"],
        "pros": ["Iconic cultural events and street festivals", "Ideal beach weather on all coasts", "Excellent seafood and pintxos in Basque country", "Long evenings and late-night dining"],
        "cons": ["Madrid/Seville can hit 40°C", "Many local shops close for August holidays", "Barcelona and coastal resorts extremely crowded"]
      },
      {
        "month": "August",
        "country": "Botswana",
        "best_cities_or_regions": ["Okavango Delta", "Chobe National Park", "Moremi Game Reserve", "Makgadikgadi Pans"],
        "why_visit": "August is peak dry season: wildlife concentrates around shrinking waterholes and the flooded Okavango Delta, producing arguably Africa's best game viewing with elephants, lions and wild dogs.",
        "climate": {"avg_temp_c": "8-28", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "600-1500",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Peak Okavango floodwaters (mokoro season)", "Massive elephant concentrations on Chobe River"],
        "travel_styles": ["wildlife", "nature", "adventure"],
        "pros": ["Exceptional wildlife density and visibility", "Cool, bug-free, low-malaria conditions", "Okavango floodwaters high for mokoro trips", "Big concentrations of elephants and predators"],
        "cons": ["Among the most expensive safari destinations", "Cold early-morning game drives", "Premium camps sell out 12+ months ahead"]
      },
      {
        "month": "August",
        "country": "Peru",
        "best_cities_or_regions": ["Cusco & Sacred Valley", "Machu Picchu", "Colca Canyon", "Lake Titicaca"],
        "why_visit": "August is prime dry-season weather in the Andes — sunny clear-sky days perfect for hiking the Inca Trail or Salkantay and photographing Machu Picchu without rainy-season clouds.",
        "climate": {"avg_temp_c": "6-19", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "70-150",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Pachamama Day (Aug 1)", "Arequipa Day / Fiesta de Arequipa (Aug 15)", "Dry-season Inca Trail peak"],
        "travel_styles": ["adventure", "culture", "nature"],
        "pros": ["Clearest skies of the year over Machu Picchu", "Dry, stable trail conditions for trekking", "Excellent stargazing in the Andes", "Cooler temperatures for high-altitude hiking"],
        "cons": ["Inca Trail permits sell out 4-6 months ahead", "Nighttime temperatures near freezing at altitude", "Machu Picchu crowds at peak"]
      },
      {
        "month": "August",
        "country": "Switzerland",
        "best_cities_or_regions": ["Jungfrau Region", "Zermatt", "Lucerne", "Engadine"],
        "why_visit": "August brings Switzerland's warmest hiking weather with all high-altitude trails, cable cars and mountain huts fully open — ideal for classic Alpine traverses and the Swiss National Day on Aug 1.",
        "climate": {"avg_temp_c": "12-24", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "250-500",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Swiss National Day (Aug 1)", "Lucerne Festival", "Street Parade Zürich (early August)"],
        "travel_styles": ["adventure", "nature", "wellness", "culture"],
        "pros": ["Entire high-Alpine trail and lift network open", "Wildflower meadows and glacier access at their best", "Long daylight for hut-to-hut hikes", "Fireworks and bonfires on Aug 1"],
        "cons": ["One of the world's most expensive destinations", "Popular trails very busy", "Afternoon thunderstorms common in mountains"]
      },
      {
        "month": "August",
        "country": "Japan",
        "best_cities_or_regions": ["Aomori", "Tokushima", "Kyoto", "Hokkaido"],
        "why_visit": "August is Japan's vibrant matsuri season — Aomori Nebuta, Tokushima's Awa Odori dance festival and Obon ancestor observances fill the streets, while Hokkaido offers cool lavender-scented escape.",
        "climate": {"avg_temp_c": "23-34", "rainfall_level": "medium", "humidity": "high"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "120-250",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Aomori Nebuta Matsuri (Aug 2-7)", "Awa Odori Tokushima (Aug 12-15)", "Obon festival (mid-August)", "Kyoto Gozan Okuribi (Aug 16)"],
        "travel_styles": ["culture", "food", "nature"],
        "pros": ["Some of Japan's most spectacular traditional festivals", "Fireworks (hanabi) displays nearly every weekend", "Hokkaido offers cool-weather alternative", "Festive street-food nights"],
        "cons": ["Hot and very humid in cities", "Typhoon season begins", "Obon week sees domestic travel surges"]
      },
      {
        "month": "August",
        "country": "United States",
        "best_cities_or_regions": ["Denali National Park", "Kenai Fjords", "Katmai", "Anchorage"],
        "why_visit": "August in Alaska is peak viewing for brown bears feasting on salmon runs at Katmai's Brooks Falls, calving glaciers in Kenai Fjords, and early autumn colors painting Denali's tundra.",
        "climate": {"avg_temp_c": "8-18", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "250-500",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Brown bear salmon run at Brooks Falls (peak)", "Alaska State Fair Palmer (late Aug-early Sep)", "Tundra fall color begins late August"],
        "travel_styles": ["wildlife", "nature", "adventure"],
        "pros": ["World-class bear viewing at Brooks Falls", "Whale watching at its peak", "Long daylight with early aurora possible late month", "Fall colors begin in Denali"],
        "cons": ["Mosquitoes and biting flies still active", "Frequent coastal rain and fog", "Lodges near Katmai/Denali book a year ahead"]
      }
    ],
    "September": [
      {
        "month": "September",
        "country": "Italy",
        "best_cities_or_regions": ["Tuscany", "Rome", "Amalfi Coast", "Venice"],
        "why_visit": "September offers Italy at its most pleasant — warm seas without August heat, grape harvest (vendemmia) in Tuscany, and the Venice International Film Festival in early September.",
        "climate": {"avg_temp_c": "17-28", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-300",
        "season_type": "shoulder",
        "crowd_level": "high",
        "key_events": ["Venice International Film Festival (late Aug-early Sep)", "Regata Storica Venice (first Sun of Sep)", "Tuscany grape harvest"],
        "travel_styles": ["culture", "food", "beach", "wellness"],
        "pros": ["Warm swimming weather without August heat and closures", "Harvest season: fresh wine, truffle previews", "Slightly thinner crowds than July/August", "Clear light ideal for photography"],
        "cons": ["Still busy and pricey at top sites", "Occasional early-autumn thunderstorms", "Film Festival boosts Venice costs"]
      },
      {
        "month": "September",
        "country": "Turkey",
        "best_cities_or_regions": ["Istanbul", "Cappadocia", "Ephesus", "Antalya"],
        "why_visit": "September delivers ideal weather nationwide — warm Aegean swimming, cool-morning hot-air balloon flights in Cappadocia, and minimal rain for exploring ancient ruins without summer's scorching heat.",
        "climate": {"avg_temp_c": "17-29", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "60-130",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Cappadox Festival Cappadocia", "Istanbul Biennial (biennial)", "Victory Day (Aug 30 celebrations extending)"],
        "travel_styles": ["culture", "adventure", "food", "beach"],
        "pros": ["Reliable balloon-flight conditions in Cappadocia", "Mediterranean/Aegean still warm for swimming", "Among Europe's most affordable destinations", "Lower crowds at top sites"],
        "cons": ["Istanbul still warm and busy", "Lira volatility makes pricing unpredictable", "Popular balloon slots book out"]
      },
      {
        "month": "September",
        "country": "Rwanda",
        "best_cities_or_regions": ["Volcanoes National Park", "Kigali", "Nyungwe Forest", "Lake Kivu"],
        "why_visit": "September is the tail end of the long dry season — ideal for gorilla trekking on firmer forest trails, plus the annual Kwita Izina gorilla-naming ceremony celebrating baby gorillas born that year.",
        "climate": {"avg_temp_c": "15-27", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "500-1500",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Kwita Izina gorilla naming ceremony (early September)", "Rwanda Film Festival", "End of long dry season"],
        "travel_styles": ["wildlife", "adventure", "nature", "culture"],
        "pros": ["Firmer, drier trails for gorilla and chimp trekking", "Kwita Izina ceremony a unique cultural highlight", "Clear views of the Virunga volcanoes", "Combines well with Serengeti/Mara"],
        "cons": ["Gorilla permits cost $1,500 per person", "Short rains may begin late September", "Permits and top lodges sell out 6-12 months ahead"]
      },
      {
        "month": "September",
        "country": "Nepal",
        "best_cities_or_regions": ["Kathmandu Valley", "Annapurna region", "Khumbu region", "Upper Mustang"],
        "why_visit": "September marks the end of monsoon and start of Nepal's prime trekking season — rain-washed clear air reveals the Himalayas, lush green terraced valleys, and fewer trekkers than October.",
        "climate": {"avg_temp_c": "15-27", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "40-90",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Teej Festival", "Indra Jatra Kathmandu (mid-September)", "End of monsoon transition"],
        "travel_styles": ["adventure", "culture", "nature", "wellness"],
        "pros": ["Exceptionally clear Himalayan views post-monsoon", "Lush green landscapes with full rivers", "Quieter trails than peak October", "Indra Jatra masked processions in Kathmandu"],
        "cons": ["Early-month rainfall, muddy trails, leeches at lower elevations", "Occasional Lukla flight delays", "Rain-shadow regions preferable if monsoon lingers"]
      },
      {
        "month": "September",
        "country": "Argentina",
        "best_cities_or_regions": ["Buenos Aires", "Península Valdés", "Mendoza", "Salta"],
        "why_visit": "September is early spring — jacaranda buds in Buenos Aires, peak southern right whale season at Península Valdés, and warm dry days in Salta with far fewer crowds than peak summer.",
        "climate": {"avg_temp_c": "10-21", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "80-180",
        "season_type": "shoulder",
        "crowd_level": "low",
        "key_events": ["Peak southern right whale season at Península Valdés", "Magellanic penguins begin arriving", "Tango Buenos Aires Festival programming"],
        "travel_styles": ["wildlife", "culture", "food", "nature"],
        "pros": ["Outstanding whale watching close to shore at Valdés", "Pleasant, dry weather in BA and the north", "Shoulder-season prices and minimal crowds", "Good time for Mendoza wine country pre-harvest"],
        "cons": ["Southern Patagonia still cold with limited services", "Unpredictable Patagonian weather", "Some hiking trails not yet open in the far south"]
      },
      {
        "month": "September",
        "country": "Germany",
        "best_cities_or_regions": ["Munich", "Berlin", "Romantic Road", "Black Forest"],
        "why_visit": "September means Oktoberfest in Munich (Sep 19 – Oct 4, 2026) — the world's largest folk festival — plus mild weather for Rhine Valley wine harvest and exploring Bavaria.",
        "climate": {"avg_temp_c": "10-20", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "130-260",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Oktoberfest Munich (Sep 19 – Oct 4, 2026)", "Cannstatter Volksfest Stuttgart (late Sep)", "Rhine in Flames final show", "Berlin Marathon (late September)"],
        "travel_styles": ["culture", "food", "nightlife"],
        "pros": ["Iconic Oktoberfest experience", "Comfortable temperatures for sightseeing and biking", "Wine harvest festivals along the Rhine and Moselle", "Berlin Marathon is a world-major"],
        "cons": ["Munich hotels charge 3-5x normal during Oktoberfest", "Tent reservations require months ahead", "Unpredictable showers and cooler evenings"]
      }
    ],
    "October": [
      {
        "month": "October",
        "country": "Japan",
        "best_cities_or_regions": ["Kyoto", "Nikko", "Kamikochi", "Tokyo"],
        "why_visit": "October brings the early koyo (autumn foliage) season in higher elevations and comfortable dry weather across most of the country — ideal for temple-hopping, hiking and food tours before peak November leaf-peeping.",
        "climate": {"avg_temp_c": "15-22", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "120-200",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Jidai Matsuri (Kyoto, Oct 22)", "Kurama Fire Festival (Oct 22)", "Tokyo Ramen Festival", "Early koyo in Japanese Alps & Hokkaido"],
        "travel_styles": ["culture", "food", "nature", "adventure"],
        "pros": ["Crisp, dry weather with low typhoon risk late in month", "Stunning early autumn colors in mountains", "Excellent seasonal cuisine", "Shoulder pricing before November peak"],
        "cons": ["Still-high domestic demand on weekends", "Costs rising as yen strengthens", "Typhoons possible in early October"]
      },
      {
        "month": "October",
        "country": "Nepal",
        "best_cities_or_regions": ["Kathmandu", "Pokhara", "Everest Base Camp", "Annapurna Circuit"],
        "why_visit": "October is the single best trekking month in Nepal — post-monsoon skies deliver crystal-clear Himalayan views, stable trails and mild temperatures, coinciding with the Dashain festival.",
        "climate": {"avg_temp_c": "10-24", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "35-70",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Dashain festival", "Tihar (late Oct/early Nov)", "Peak Himalayan trekking season"],
        "travel_styles": ["adventure", "nature", "culture", "wellness"],
        "pros": ["Clearest mountain views of the year", "Perfect trekking weather", "Vibrant Dashain cultural celebrations", "Affordable for serious adventure travel"],
        "cons": ["Trails and teahouses crowded on popular routes", "Flights to Lukla prone to delays", "Permits book up fast"]
      },
      {
        "month": "October",
        "country": "Namibia",
        "best_cities_or_regions": ["Etosha National Park", "Sossusvlei", "Swakopmund", "Damaraland"],
        "why_visit": "October is peak dry-season wildlife viewing — animals concentrate around Etosha's waterholes, making it one of Africa's best months for big-game sightings before the rains arrive.",
        "climate": {"avg_temp_c": "15-33", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-300",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Peak Etosha game viewing", "Windhoek Oktoberfest (late Oct)", "Sossusvlei dune photography season"],
        "travel_styles": ["wildlife", "adventure", "nature"],
        "pros": ["Exceptional waterhole game viewing", "Dry clear skies for stargazing", "Empty dune landscapes at Sossusvlei", "Low malaria risk in most areas"],
        "cons": ["Daytime heat can exceed 35°C", "Lodges at peak pricing", "Long self-drive distances"]
      },
      {
        "month": "October",
        "country": "United States",
        "best_cities_or_regions": ["Vermont", "White Mountains", "Acadia", "Upstate New York"],
        "why_visit": "Peak New England fall foliage sweeps south through October, producing some of the world's most spectacular autumn color alongside harvest festivals, cider mills and covered-bridge drives.",
        "climate": {"avg_temp_c": "5-18", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "180-320",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Peak fall foliage (early-mid Oct)", "Stowe Foliage Arts Festival", "Keene Pumpkin Festival", "Salem Haunted Happenings"],
        "travel_styles": ["nature", "culture", "food"],
        "pros": ["World-famous autumn foliage", "Cool hiking weather", "Apple/pumpkin harvest festivals", "Halloween atmosphere in Salem"],
        "cons": ["'Leaf-peeper' crowds and booked-out inns", "Two-night minimums common on weekends", "Higher rates than summer in some towns"]
      },
      {
        "month": "October",
        "country": "Turkey",
        "best_cities_or_regions": ["Istanbul", "Cappadocia", "Pamukkale", "Antalya coast"],
        "why_visit": "October offers warm-but-comfortable days, clear skies ideal for Cappadocia balloon rides, and the Mediterranean still warm enough for swimming without summer's heat and crowds.",
        "climate": {"avg_temp_c": "14-24", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "60-120",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Akbank Jazz Festival Istanbul", "Cappadox-adjacent balloon season peak", "Republic Day (Oct 29)", "Antalya Golden Orange Film Festival"],
        "travel_styles": ["culture", "food", "adventure", "beach"],
        "pros": ["Ideal ballooning weather in Cappadocia", "Mediterranean still swimmable", "Shoulder-season pricing", "Fewer cruise crowds in Istanbul"],
        "cons": ["Inflation makes prices volatile", "Eastern Turkey gets cold quickly", "Some coastal resorts wind down late month"]
      }
    ],
    "November": [
      {
        "month": "November",
        "country": "Vietnam",
        "best_cities_or_regions": ["Hoi An", "Da Nang", "Hanoi", "Ha Long Bay"],
        "why_visit": "Central Vietnam emerges from the rainy season in November with sunny dry weather — perfect for beaches, lantern-lit Hoi An strolls and exploring the Cham ruins without summer's intense heat.",
        "climate": {"avg_temp_c": "20-28", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "40-80",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Hoi An Full Moon Lantern Festival", "Vietnam Teachers' Day (Nov 20)", "Ha Long Bay cruise high season begins", "Sapa rice terrace harvest"],
        "travel_styles": ["culture", "food", "beach", "nature"],
        "pros": ["Excellent weather in Centre and South", "Very affordable street food and hotels", "Diving season opens in Nha Trang/Phu Quoc", "Low humidity in Hanoi"],
        "cons": ["North (Sapa) can be chilly and misty", "Occasional late typhoon on central coast", "Some rain lingers first week in Hue"]
      },
      {
        "month": "November",
        "country": "Mexico",
        "best_cities_or_regions": ["Oaxaca", "Mexico City", "Mérida", "San Miguel de Allende"],
        "why_visit": "Día de los Muertos (Nov 1-2) turns Oaxaca and Mexico City into extraordinary celebrations of marigold altars, parades and candlelit cemeteries — paired with dry, mild post-monsoon weather nationwide.",
        "climate": {"avg_temp_c": "14-26", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "80-160",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Día de los Muertos (Nov 1-2)", "CDMX Day of the Dead Parade", "Revolution Day (Nov 20)", "Festival Cervantino tail end"],
        "travel_styles": ["culture", "food", "nightlife"],
        "pros": ["Iconic Day of the Dead experience", "Ideal dry-season weather", "World-class mezcal and mole in Oaxaca", "Beach season ramping up"],
        "cons": ["Oaxaca hotels triple in price & sell out", "Flights expensive around Nov 1-2", "Crowds at famous cemeteries"]
      },
      {
        "month": "November",
        "country": "Oman",
        "best_cities_or_regions": ["Muscat", "Wahiba Sands", "Jebel Akhdar", "Musandam Peninsula"],
        "why_visit": "November marks the return of comfortable desert temperatures and calm seas — perfect for dune camping, wadi swimming, turtle nesting at Ras al Jinz and dhow cruising in the Musandam fjords.",
        "climate": {"avg_temp_c": "22-30", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "130-250",
        "season_type": "high",
        "crowd_level": "low",
        "key_events": ["Turtle nesting at Ras al Jinz", "Muscat Festival prep/early events", "National Day (Nov 18)", "Diving high season in Daymaniyat Islands"],
        "travel_styles": ["adventure", "nature", "culture", "wildlife"],
        "pros": ["Ideal desert and beach weather", "Few tourists relative to UAE", "Great for families and self-drives", "Rich, safe cultural travel"],
        "cons": ["Higher costs than regional neighbors", "Limited nightlife / alcohol restrictions", "Distances between sights are long"]
      },
      {
        "month": "November",
        "country": "India",
        "best_cities_or_regions": ["Jaipur & Rajasthan", "Varanasi", "Delhi", "Kerala backwaters"],
        "why_visit": "Diwali falls on November 8, 2026, lighting up cities with lamps, sweets and fireworks; cool dry weather across the north makes this the best month for Golden Triangle touring and Rajasthan desert trips.",
        "climate": {"avg_temp_c": "12-28", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "45-100",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Diwali (Nov 8, 2026)", "Pushkar Camel Fair", "Guru Nanak Jayanti (Nov 24)", "Dev Deepawali in Varanasi (late Nov)"],
        "travel_styles": ["culture", "food", "wellness"],
        "pros": ["Perfect touring weather in the north", "Witness Diwali celebrations", "Pushkar Fair is a bucket-list spectacle", "Great value for heritage hotels"],
        "cons": ["Delhi air quality very poor post-Diwali", "Trains and flights book out around festivals", "Some shops/sites close on Diwali day"]
      },
      {
        "month": "November",
        "country": "Argentina",
        "best_cities_or_regions": ["Buenos Aires", "El Calafate/El Chaltén", "Mendoza", "Iguazú Falls"],
        "why_visit": "Spring in Argentina means jacaranda-lined Buenos Aires streets, long daylight hours in Patagonia for glacier trekking before summer winds peak, and Mendoza vineyards waking up for the season.",
        "climate": {"avg_temp_c": "10-25", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "90-170",
        "season_type": "shoulder",
        "crowd_level": "medium",
        "key_events": ["Día de la Tradición (Nov 10)", "Buenos Aires Jazz Festival", "Creamfields BA", "Start of Patagonia trekking season"],
        "travel_styles": ["adventure", "nature", "food", "culture"],
        "pros": ["Patagonia accessible with fewer crowds than January", "Jacarandas in bloom in BA", "Wine harvest prep in Mendoza", "Favourable exchange rates"],
        "cons": ["Patagonia weather still unpredictable", "Peso volatility affects pricing", "Some Torres del Paine refugios not fully open until mid-Nov"]
      }
    ],
    "December": [
      {
        "month": "December",
        "country": "Finland",
        "best_cities_or_regions": ["Rovaniemi", "Levi", "Helsinki", "Saariselkä"],
        "why_visit": "December in Lapland means Santa's hometown, reindeer sleigh rides, snow-covered forests and prime northern lights viewing during the polar night — an iconic family and aurora destination.",
        "climate": {"avg_temp_c": "-15 to -3", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "250-500",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Santa Claus Village year-round peak", "Independence Day (Dec 6)", "Helsinki Christmas Market (Tuomaan Markkinat)", "Aurora borealis viewing peak"],
        "travel_styles": ["skiing", "adventure", "nature", "wellness"],
        "pros": ["Magical Arctic Christmas atmosphere", "Excellent aurora viewing", "Husky sledding, ice fishing, saunas", "Well-organized family activities"],
        "cons": ["Very expensive in peak Christmas week", "Extreme cold and minimal daylight", "Glass igloos book 6-12 months ahead"]
      },
      {
        "month": "December",
        "country": "Thailand",
        "best_cities_or_regions": ["Bangkok", "Chiang Mai", "Krabi/Railay", "Koh Lanta"],
        "why_visit": "December is peak dry season with sunny warm days, calm Andaman seas perfect for islands and diving, and festive New Year celebrations across Bangkok's rooftops and southern beaches.",
        "climate": {"avg_temp_c": "22-32", "rainfall_level": "low", "humidity": "medium"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "60-130",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["King's Birthday (Dec 5)", "Chiang Mai Red Cross Winter Fair", "NYE fireworks on Bangkok riverside", "Full Moon Party Koh Phangan"],
        "travel_styles": ["beach", "food", "nightlife", "culture"],
        "pros": ["Reliably sunny across the country", "Great diving visibility in Andaman", "Excellent street food scene", "Good value even in high season"],
        "cons": ["Hotel rates spike 30-50% over Christmas/NYE", "Popular islands very crowded", "Advance booking essential"]
      },
      {
        "month": "December",
        "country": "Germany",
        "best_cities_or_regions": ["Nuremberg", "Munich", "Dresden", "Cologne"],
        "why_visit": "Germany's Christkindlmärkte transform town squares with glühwein, gingerbread and timbered charm from late November through December 23 — the world's original and best Christmas markets.",
        "climate": {"avg_temp_c": "-2 to 5", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "mid-range",
        "estimated_daily_cost_usd": "150-280",
        "season_type": "high",
        "crowd_level": "high",
        "key_events": ["Nuremberg Christkindlesmarkt", "Dresden Striezelmarkt (oldest in Germany)", "Munich Christkindlmarkt at Marienplatz", "Cologne Cathedral Christmas Market"],
        "travel_styles": ["culture", "food", "nightlife"],
        "pros": ["Iconic, atmospheric Christmas markets", "Excellent rail connections between cities", "Superb beer, wine and hearty winter food", "Many museums uncrowded midweek"],
        "cons": ["Cold, often grey/wet weather", "Most markets close by Dec 23-24", "Hotel rates peak on market weekends"]
      },
      {
        "month": "December",
        "country": "New Zealand",
        "best_cities_or_regions": ["Queenstown", "Milford Sound", "Bay of Islands", "Wellington"],
        "why_visit": "Early summer brings long daylight (up to 15+ hours), blooming lupins in the Mackenzie region and ideal conditions for Great Walks, kayaking and road trips before peak-January crowds and prices.",
        "climate": {"avg_temp_c": "10-22", "rainfall_level": "medium", "humidity": "medium"},
        "budget_category": "luxury",
        "estimated_daily_cost_usd": "200-380",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Rhythm & Vines Festival (Gisborne, Dec 29-31)", "Lupin blooms Lake Tekapo", "Summer Great Walks open", "Kiwi beach holidays begin"],
        "travel_styles": ["adventure", "nature", "wildlife"],
        "pros": ["Long daylight hours for exploring", "Fewer crowds than January peak", "Great Walks fully open", "Stunning lupin and pōhutukawa blooms"],
        "cons": ["Rates climb sharply after Dec 20", "Fiordland still wet and midge-prone", "Campervans and hikes book out far ahead"]
      },
      {
        "month": "December",
        "country": "Ethiopia",
        "best_cities_or_regions": ["Lalibela", "Gondar", "Simien Mountains", "Addis Ababa"],
        "why_visit": "December is the heart of the dry Bega season — clear skies, cool highland temperatures and excellent trekking conditions, plus Genna (Ethiopian Christmas) preparations and vibrant northern pilgrimage routes.",
        "climate": {"avg_temp_c": "10-24", "rainfall_level": "low", "humidity": "low"},
        "budget_category": "budget",
        "estimated_daily_cost_usd": "60-130",
        "season_type": "high",
        "crowd_level": "medium",
        "key_events": ["Preparations for Genna (Jan 7)", "Peak Simien Mountains trekking", "Omo Valley cultural ceremonies", "Run-up to Timkat (Jan 19)"],
        "travel_styles": ["culture", "adventure", "nature"],
        "pros": ["Dry, cool weather ideal for trekking", "Clear skies for photography at Lalibela", "Access to Omo Valley tribal visits", "Leads into January's Timkat festival"],
        "cons": ["Top lodges book up a year ahead", "Peak-season pricing on guides and flights", "Altitude (2,000-4,000m) affects some travelers"]
      }
    ]
  },
  "example_filter_queries": [
    {
      "query": "March + budget + low crowds",
      "explanation": "Shoulder-season picks in March that combine affordable daily costs (under ~$150/day) with medium-to-low crowds — ideal for travelers wanting warm-weather value without tourist bottlenecks.",
      "matches": [
        {
          "country": "Sri Lanka",
          "match_reason": "Budget category (USD 45-100/day), dry-season south/west coast, medium crowd level. Great pair of beach + leopard safari at Yala before April price rises."
        },
        {
          "country": "Jordan",
          "match_reason": "Mid-range but low-cost by regional standards (USD 90-170/day), shoulder season with medium crowds at Petra and Wadi Rum, cool desert weather and wildflower blooms."
        },
        {
          "country": "South Africa",
          "match_reason": "Shoulder season with medium crowds in Cape region; strong USD gives mid-range travelers luxury-tier value at wine estates and Kruger lodges (USD 100-200/day)."
        }
      ]
    },
    {
      "query": "July + luxury + beach + high season",
      "explanation": "Peak summer destinations pairing luxury price points with world-class beach access during their high season.",
      "matches": [
        {
          "country": "Greece",
          "match_reason": "High season with luxury budget (USD 150-350/day); travel_styles include beach, culture, food and nightlife. Classic Aegean island-hopping with hot dry weather and open-air festivals."
        },
        {
          "country": "Tanzania",
          "match_reason": "Luxury category (USD 400-900/day), high season with beach style included — the iconic Serengeti-plus-Zanzibar combo peaks in July with dry safari weather and warm Indian Ocean swimming."
        },
        {
          "country": "Iceland",
          "match_reason": "Luxury high-season pick (USD 200-400/day). Not tropical beach, but includes coastal nature with black-sand beaches, puffin cliffs and midnight-sun coastal drives — the premium Nordic summer alternative."
        }
      ]
    },
    {
      "query": "November + mid-range + cultural travel",
      "explanation": "November options with mid-range daily costs and 'culture' listed prominently in travel_styles, ideal for festival-driven trips without luxury pricing.",
      "matches": [
        {
          "country": "Mexico",
          "match_reason": "Mid-range (USD 80-160/day) with culture, food and nightlife styles — Día de los Muertos in Oaxaca and Mexico City is one of the world's great cultural spectacles."
        },
        {
          "country": "Argentina",
          "match_reason": "Mid-range (USD 90-170/day) with culture, food, adventure — Día de la Tradición, tango festivals, and jacaranda-lined Buenos Aires at its cultural peak."
        },
        {
          "country": "Oman",
          "match_reason": "Mid-range (USD 130-250/day) with culture and heritage experiences — National Day celebrations on Nov 18, traditional souks in Muscat, low crowds make cultural immersion easier."
        }
      ]
    }
  ]
};
